app/urls.py
from django.urls import path, re_path
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.pagina_principal, name='pagina_princial'),
    path('figura_detalle/<int:id>/', views.figura_detalle_view, name='figura_detalle'),
    path('area_detalle/<nombre>/', views.area_detalle_view, name='area_detalle'),
    path('categoria_detalle/<nombre>/', views.categoria_detalle_view, name='categoria_detalle'),
    path('login/', views.iniciar_sesion, name='iniciar_sesion'),
    path('logout/', views.cerrar_sesion, name='cerrar_sesion'),
    path('registro/', views.registrarse, name='registrarse'),
    path('anadirPregunta/', views.anadirPregunta,name='anadirPregunta'),
    re_path(r'^figuras/$', views.FiguraListView.as_view(), name='figuras'),
    re_path(r'^misjuegos/$', views.MisJuegos, name='misjuegos'),
    re_path(r'^areas/$', views.AreaListView.as_view(), name='areas'),
    re_path(r'^categorias/$', views.CategoriaListView.as_view(), name='categorias'),
    re_path(r'^curiosidades/$', views.CuriosidadListView.as_view(), name='curiosidades'),
    re_path(r'^recursos/$', views.RecursoListView.as_view(), name='recursos'),


]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from app import views


app_name = 'app'

urlpatterns = [
    path('', views.pagina_principal, name='pagina_principal'),
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

]


urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

templates/User_login.html
{% extends 'app/base.html' %}

    {% block title_block %}
        Login
    {% endblock %}

    {% block body_block %}
    {% if user.is_authenticated %}
        <error>{{error}}</error>
       <p> Hi {{nombre}}you are already logged in.</p>
       <p>If you want to log in with another account please log-out before.</p>
    {% else %}
        <h1>Please login to access this web site</h1>
        <form id="login_form" method="post" action="{% url 'app:iniciar_sesion' %}">
            {% csrf_token %}
            Nombre de usuario: <input type="text" name="username" value="" size="50" />
            <br><br>
            Contrasena: <input type="password" name="password" value="" size="50" />
            <br><br>
            <input type="submit" value="login" />
        </form>
    </br>
        <error>{{error}}</error>
    {% endif %}
    {% endblock %}