app/urls.py
from django.urls import path, re_path
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.pagina_principal, name='pagina_princial'),
    path('figura_detalle/<int:id>/', views.figura_detalle_view, name='figura_detalle'),
    path('area_detalle/<nombre>/', views.area_detalle_view, name='area_detalle'),
    path('categoria_detalle/<nombre>/', views.categoria_detalle_view, name='categoria_detalle'),
    path('login/', views.iniciar_sesion, name='iniciar_sesion'),
    path('logout/', views.cerrar_sesion, name='cerrar_sesion'),
    path('registro/', views.registrarse, name='registrarse'),
    path('anadirPregunta/', views.anadirPregunta,name='anadirPregunta'),
    re_path(r'^figuras/$', views.FiguraListView.as_view(), name='figuras'),
    re_path(r'^misjuegos/$', views.MisJuegos, name='misjuegos'),
    re_path(r'^areas/$', views.AreaListView.as_view(), name='areas'),
    re_path(r'^categorias/$', views.CategoriaListView.as_view(), name='categorias'),
    re_path(r'^curiosidades/$', views.CuriosidadListView.as_view(), name='curiosidades'),
    re_path(r'^recursos/$', views.RecursoListView.as_view(), name='recursos'),


]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from app import views


app_name = 'app'

urlpatterns = [
    path('', views.pagina_principal, name='pagina_principal'),
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

]


urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

app/templates/app/anadirPregunta.html
{% extends "base.html" %} 
{% block content %}
<style>
    h1 {
      font-family: 'Playfair Display', serif;
      font-size: 30px;
      text-align: left;  
    }
    h2{
      font-family: 'Playfair Display', serif;
      font-size: 30px;
      text-align: left
    }
  
    #href{
      font-family: 'Playfair Display', serif;
      font-size: 18px;
      text-align: left
    }
    #inv{
      font-family: 'Playfair Display', serif;
      text-align: center;
      font-size: 18px;
    }
    .formu{
      font-family: 'Playfair Display', serif;
      text-align: center;
      font-size: 18px;
    }
    .jumbotron{
      font-family: 'Playfair Display', serif;
      text-align: center;
      font-size: 18px;
      margin-left: 400px;
    }
  </style>
<div class="jumbotron container row">
    <div class="col-md-6">
        <h1>Admin, aqui puedes añadir una pregunta</h1>
        <div class="card card-body">
           <form class = "form" action="" method="POST">
              {% csrf_token %}
                {{form.as_p}}
                <br>
             <input class = "formu" type="submit" name="Submit">
             </form>
            </div>
        </div>
    </div>
 
</div>
 
{% endblock %}

app/templates/app/area_detalle.html
{% extends "base.html" %}

{% block content %}
<style>
  h1 {
    font-family: 'Playfair Display', serif;
    font-size: 80px;
    text-align: center;  
  }
  h2{
    font-family: 'Playfair Display', serif;
    font-size: 18px;
    background: rgb(78, 91, 105); 
    color:  rgb(0, 0, 0); 
    font-weight: bold; 
    padding: 15px; 
    border: 2px solid rgb(78, 91, 105); 
    border-radius: 6px;
  }
  h5{
    font-family: 'Playfair Display', serif;
    font-size: 45px;
    background: rgb(78, 91, 105); 
    color:  rgb(0, 0, 0); 
    font-weight: bold; 
    padding: 15px; 
    border: 2px solid rgb(78, 91, 105); 
    border-radius: 6px;
  }
  #nombre{
      font-family: 'Playfair Display', serif;
      text-align: center;
      font-size: 20px;
      color: rgb(47, 0, 255);
    }
    h5{
    font-family: 'Playfair Display', serif;
    font-weight: bold;
    font-size: 30px
  }
  p{
    font-family: 'Playfair Display', serif;
  }
</style>
  <!-- carousel start -->
      {% if figuras %}
        <div class="row row-cols-1 row-cols-md-3">
            {% for figura in figuras %}
              <div class="col md-4">
                <div class="card h-100">
                {% if figura.imagen1 %}
                  <img src="{{figura.imagen1.url}}" class="card-img-top" alt="...">
                  {% endif %}
                  <div class="card-body">
                    <h5 class="card-title">{{figura.nombre}} {{figura.apellido}}</h5>
                    <p class="card-text">{{figura.art.titulo}}</p>
                    <a href="{% url 'app:figura_detalle' figura.id %}" id="nombre"> Pulse aquí para más información sobre {{figura.nombre}}</a>
                  </div>
                </div>
              </div>
            {% endfor %} 
    {% else %} 
      <h1> No existen figuras registradas </h1>
    {% endif %}
  <!-- carousel end -->

{% endblock %}

app/templates/app/area_list.html
{% extends "base.html" %}

{% block content %}
<style>
    h1 {
      font-family: 'Playfair Display', serif;
      font-size: 80px;
      text-align: center;  
    }
    #nombre{
      font-family: 'Playfair Display', serif;
      text-align: center;
      font-size: 40px;
      color: rgb(83, 78, 78);
    }
    #areas{
        margin-top: 70px;
        text-align: center;
    }
    #ref{
      font-family: 'Playfair Display', serif;
      text-align: center;
      font-size: 18px;
      color: rgb(0, 0, 0);
      margin-left: 30px;
    }
    #sig{
      font-family: 'Playfair Display', serif;
      text-align: center;
      font-size: 18px;
      color: rgb(38, 0, 255);
      font-weight: bold;
      margin-left: 30px;

    }
  </style>
    <h1>Areas cientificas disponibles</h1>
  {% if areas %}
          {% for area in areas %}
          <div id = "areas">
            <a href="{% url 'app:area_detalle' area.nombre %}" id="nombre">{{ area.nombre }}</a>
            <br>
          </div>
                
          {% endfor %}
          <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}" id ="sig" >Anterior</a>
                {% endif %}

                <span class="current" id ="ref">
                    Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" id ="sig">Siguiente</a>
                {% endif %}
            </span>
        </div>  
{% else %} 
  <h1> No existen areas registradas </h1>
{% endif %}

{% endblock %}

app/templates/app/categoria_detalle.html
{% extends "base.html" %} 
{% block content %}
<style>
    h1 {
      font-family: 'Playfair Display', serif;
      font-size: 80px;
      text-align: center;  
    }
    #cambio{
      font-family: 'Playfair Display', serif;
      text-align: left
    }
    .formu{
    font-family: 'Playfair Display', serif;
    text-align: center;
    font-size: 18px;
    }
    #timer{
    font-family: 'Playfair Display', serif;
      text-align: left
    }

  </style>
    {% load static %}
    <div class="container ">
    <h1>¡Bienvenido al cuestionario!</h1>
    
    <div align="right " id="displaytimer"><b>Timer: 0 seconds</b></div>
    
    <form method='post' action=''>
        {% csrf_token %}
            {% for p in preguntas%}
            <div class="form-group">
            <label id = "cambio" for="pregunta">{{p.pregunta}}</label>
            </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="{{p.pregunta}}" id="gridRadios1" value="option1" checked>
                    <label id = "cambio" class="form-check-label" for="gridRadios1">
                        {{p.op1}}
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="{{p.pregunta}}" id="gridRadios2" value="option2">
                    <label id = "cambio" class="form-check-label" for="gridRadios2">
                        {{p.op2}}
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="{{p.pregunta}}" id="gridRadios1" value="option3">
                    <label id = "cambio" class="form-check-label" for="gridRadios1">
                        {{p.op3}}
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="{{p.pregunta}}" id="gridRadios2" value="option4">
                    <label id = "cambio" class="form-check-label" for="gridRadios2">
                        {{p.op4}}
                    </label>
                </div>
                <br>
            {% endfor %}
        <input id='timer' type='hidden' name="timer" value="">
        <br>
        <button class = "formu" type="submit" class="btn btn-primary">¡Quiero ver mis resultados!</button>
    </form>
        {% block script %}
            <script>
    
                console.log('hello world')
                const timer=document.getElementById('displaytimer')
                console.log(timer.textContent)
                const inputtag = document.getElementById('timer')
    
                t=0
                setInterval(()=>{
                    t+=1
                    timer.innerHTML ="<b>Tiempo: " +t+" segundos</b>"
                    inputtag.value = t
                },1000)
            </script>
        {% endblock script %}
    
    </div>
{% endblock %}

app/templates/app/categoria_list.html
{% extends "base.html" %}

{% block content %}
<style>
    h1 {
      font-family: 'Playfair Display', serif;
      font-size: 80px;
      text-align: center;  
    }
    #boton{
      font-family: 'Playfair Display', serif;
      text-align: left;
      font-size: 30px;
    }
    #ref{
      font-family: 'Playfair Display', serif;
      text-align: center;
      font-size: 18px;
      color: rgb(0, 0, 0);
      margin-left: 30px;
    }
    #sig{
      font-family: 'Playfair Display', serif;
      text-align: center;
      font-size: 18px;
      color: rgb(38, 0, 255);
      font-weight: bold;
      margin-left: 30px;

    }
</style>
    <h1>Cuestionarios disponibles</h1>
  {% if categorias %}
  <br>
  <br>
          {% for categoria in categorias %}
          <div class="container">
            <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
              <div class="col">
                <div class="p-3 border bg-light"><a href="{% url 'app:categoria_detalle' categoria.nombre %}" id = "boton" class="btn btn-success">¡Haz un quiz sobre {{categoria.nombre}}!</a>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}" id ="sig" >Anterior</a>
                {% endif %}

                <span class="current" id ="ref">
                    Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" id ="sig">Siguiente</a>
                {% endif %}
            </span>
        </div>    
{% else %} 
  <h1> No existen categorias registradas </h1>
{% endif %}

{% endblock %}

app/templates/app/curiosidad_list.html
{% extends "base.html" %}

{% block content %}
<style>
    h1 {
      font-family: 'Playfair Display', serif;
      font-size: 80px;
      text-align: center;  
    }
    h2{
      font-family: 'Playfair Display', serif;
      text-align: left
    }
    #ref{
      font-family: 'Playfair Display', serif;
      text-align: center;
      font-size: 18px;
      color: rgb(0, 0, 0);
      margin-left: 30px;
    }
    #sig{
      font-family: 'Playfair Display', serif;
      text-align: center;
      font-size: 18px;
      color: rgb(38, 0, 255);
      font-weight: bold;
      margin-left: 30px;
      margin-bottom: 30px;
    }
    h5{
    font-family: 'Playfair Display', serif;
    font-weight: bold;
    font-size: 30px
  }
  p{
    font-family: 'Playfair Display', serif;
  }
</style>
    <h1>Descubre curiosidades sobre las mujeres que cambiaron el mundo</h1>
      {% if curiosidades %}
        <div class="row row-cols-1 row-cols-md-3">
            {% for curiosidad in curiosidades %}
              <div class="col md-4">
                <div class="card h-100" style="width: 400px; height: 400px;">
                {% if curiosidad.imagen %}
                  <img src="{{curiosidad.imagen.url}}" class="card-img-top" alt="...">
                  {% endif %}
                  <div class="card-body">
                    <h5 class="card-title">{{curiosidad.titulo}}</h5>
                    <p class="card-text">{{curiosidad.resumen}}</p>
                  </div>
                </div>
              </div>
            {% endfor %}
            <div class="pagination">
              <span class="step-links">
                  {% if page_obj.has_previous %}
                      <a href="?page={{ page_obj.previous_page_number }}" id ="sig" >Anterior</a>
                  {% endif %}
  
                  <span class="current" id ="ref">
                      Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                  </span>
  
                  {% if page_obj.has_next %}
                      <a href="?page={{ page_obj.next_page_number }}" id ="sig">Siguiente</a>
                  {% endif %}
              </span>
          </div>   
    {% else %} 
      <h1> No existen curiosidades registradas </h1>
    {% endif %}

{% endblock %}

app/templates/app/figura_detalle.html
{% extends "base.html" %}

{% block content %}
<style>
  h1 {
    font-family: 'Playfair Display', serif;
    font-size: 80px;
    text-align: center;  
  }
  h2{
    font-family: 'Playfair Display', serif;
    font-size: 18px;
    background: rgb(78, 91, 105); 
    color:  rgb(0, 0, 0); 
    font-weight: bold; 
    padding: 15px; 
    border: 2px solid rgb(78, 91, 105); 
    border-radius: 6px;
  }
  h5{
    font-family: 'Playfair Display', serif;
    font-size: 45px;
    background: rgb(78, 91, 105); 
    color:  rgb(0, 0, 0); 
    font-weight: bold; 
    padding: 15px; 
    border: 2px solid rgb(78, 91, 105); 
    border-radius: 6px;
  }
</style>
 <!-- carousel start -->
 <div class="bd-example">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel" style="height:1000px; width: 600px; padding: .5em; margin-top: 60px; margin-left: 600px">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{{figura.imagen1.url}}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <br>
          <br>
          <h5>{{figura.nombre}} {{figura.apellido}}</h5>
          <h2>Desliza para ver más.</h2>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{{figura.imagen2.url}}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <br>
          <br>
          <h2>{{figura.art.titulo}}.</h2>
          <h2>{{figura.art.resumen}}.</h2>

        </div>
      </div>
      <div class="carousel-item">
        <img src="{{figura.imagen3.url}}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>{{figura.nombre}} {{figura.apellido}} {{figura.fecha_de_nacimiento}} {{fecha_de_fallecimiento}}</h5>
          <h2>{{figura.area}}</h2>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
  <!-- carousel end -->
{% endblock %}

app/templates/app/figura_list.html
{% extends "base.html" %}

{% block content %}
<style>
    h1 {
      font-family: 'Playfair Display', serif;
      font-size: 80px;
      text-align: center;  
    }
    #nombre{
      font-family: 'Playfair Display', serif;
      text-align: center;
      font-size: 40px;
      color: rgb(83, 78, 78);
    }
    #figuras{
        margin-top: 70px;
        text-align: center;
    }
    #ref{
      font-family: 'Playfair Display', serif;
      text-align: center;
      font-size: 18px;
      color: rgb(0, 0, 0);
      margin-left: 30px;
    }
    #sig{
      font-family: 'Playfair Display', serif;
      text-align: center;
      font-size: 18px;
      color: rgb(38, 0, 255);
      font-weight: bold;
      margin-left: 30px;

    }
  </style>
    <h1>Mujeres científicas que cambiaron la historia</h1>
    {% if figuras %}
          {% for figura in figuras %}
          <div id = "figuras">
            <a href="{% url 'app:figura_detalle' figura.id %}" id="nombre">{{ figura.nombre }} {{figura.apellido}} : {{figura.area}}</a>
            <br>
          </div>
          
          {% endfor %}
          <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}" id ="sig" >Anterior</a>
                {% endif %}

                <span class="current" id ="ref">
                    Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" id ="sig">Siguiente</a>
                {% endif %}
            </span>
        </div> 
{% else %} 
  <h1> No existen figuras registradas </h1>
{% endif %}

{% endblock %}

app/templates/app/menu_superior.html
{% load static %}
 
<style>
  .greet{
    font-size: 20px;
    color: #fff;
    margin-right: 20px;
    font-family: 'Playfair Display', serif;

  }
  .nav-link{
    font-family: 'Playfair Display', serif;
    font-size: 20px;

  }
</style>
<head>
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,500&display=swap" rel="stylesheet"> 
  <link rel="preconnect" href="https://fonts.googleapis.com">
</head>

 
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
 
    <ul class="navbar-nav">
      
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'pagina_principal' %}">Página principal</a> 
      </li>
      </li>
      <li class="nav-item active">
        
      {% if request.user.is_staff %}
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'app:anadirPregunta' %}">Añadir Pregunta</a>
      </li>
      {% endif %} 
 
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'login' %}">Iniciar Sesión</a>
      </li>
        <a class="nav-link" href="{% url 'app:figuras' %}">Conoce todas las voces olvidadas</a>
      </li>
        <a class="nav-link" href="{% url 'app:areas' %}">Categorías</a>
      </li>
      <a class="nav-link" href="{% url 'app:curiosidades' %}">¿Sabías qué?</a>
      </li>
      </li>
      <a class="nav-link" href="{% url 'app:recursos' %}">Recursos para profundizar</a>
      </li>

      {% if user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'app:categorias' %}">Mis juegos</a> 
      </li>
      </li>
      {% endif %}
    </ul>
  </div>
 
  <span class="greet">Hola, {{request.user}}</span>
  <span ><a  class="greet" href="{% url 'logout' %}">Cerrar Sesión</a></span>
 
</nav>

app/templates/app/recurso_list.html
{% extends "base.html" %}

{% block content %}
<style>
    h1 {
      font-family: 'Playfair Display', serif;
      font-size: 80px;
      text-align: center;  
    }
    #nombre{
      font-family: 'Playfair Display', serif;
      text-align: center;
      font-size: 40px;
      color: rgb(83, 78, 78);
    }
    #recursos{
        margin-top: 70px;
        text-align: center;
    }
    #ref{
      font-family: 'Playfair Display', serif;
      text-align: center;
      font-size: 18px;
      color: rgb(0, 0, 0);
      margin-left: 30px;
    }
    #sig{
      font-family: 'Playfair Display', serif;
      text-align: center;
      font-size: 18px;
      color: rgb(38, 0, 255);
      font-weight: bold;
      margin-left: 30px;

    }
  </style>
    <h1>Recursos para profundizar</h1>
  {% if recursos %}
          {% for recurso in recursos %}
          <div id = "recursos">
            <a href="{{recurso.url}}" id="nombre">{{ recurso.titulo }}</a>
            <br>
          </div>
                
          {% endfor %} 
          <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}" id ="sig" >Anterior</a>
                {% endif %}

                <span class="current" id ="ref">
                    Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" id ="sig">Siguiente</a>
                {% endif %}
            </span>
        </div>   
{% else %} 
  <h1> No existen recursos registradas </h1>
{% endif %}

{% endblock %}

app/templates/app/registro.html
{% extends "base.html" %}

{% block content %}
<style>
    .formu{
    font-family: 'Playfair Display', serif;
    text-align: center;
    font-size: 18px;
  }
  .centro{
    margin-top: 60px;
  }
</style>

<form class = "centro" action="{% url 'app:registrarse' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class = "formu" type="submit" class="btn btn-success" id="Registrarse" value="Registrarse"></input></class>
    {% for message in messages %}
        <p class="item" id="messages">{{ message }}</p>
    {% endfor%}
</form>



{% endblock %}

app/templates/app/resultado_cuestionario.html
{% extends "base.html" %} 
 
{% block content %}
<style>
    h1 {
      font-family: 'Playfair Display', serif;
      font-size: 40px;
      text-align: center;  
    }
    .card-text, .card-title{
      font-family: 'Playfair Display', serif;
      font-size: 30px;
      text-align: center;  
    }
    .container{
      font-family: 'Playfair Display', serif;
      font-size: 18px;
      margin-left: 475px;
      margin-top: 60px;
    }
</style>
<div class="container ">
        
    <div class="card-columns" style="padding: 10px; margin: 20px;">
        <div class="card" align="centre " style="width: 50rem; border:5px black solid">
            <img class="card-img-top" src="https://logos.flamingtext.com/Word-Logos/resultados-design-china-name.png" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Puntuacion: {{puntuacion}}/{{total}}</h5>
 
                <p class="card-text">Tiempo total: {{time}} seconds</p>
                <p class="card-text">Respuestas correctas: {{n_correctas}}</p>
                <p class="card-text">Respuestas incorrectas: {{n_incorrectas}}</p>
                <!--<p class="card-text">{{lista_incorrectas}}</p>-->
                <p class="card-text">Total de preguntas: {{total}}</p>

                <h1>¡Mucha suerte en tu próximo cuestionario!</h1>
            </div>
        </div>
    </div>
</div>

<div class="container ">

    <div class="card-columns" style="padding: 10px; margin: 20px;">
        <div class="card" align="centre " style="width: 50rem; border:5px black solid">
            <img class="card-img-top" src="http://agrismartdata.com/wp-content/uploads/2019/02/Soluciones-para-agricultura-de-precisi%C3%B3n-1.jpg" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Puntuacion: {{puntuacion}}/{{total}}</h5>
                {% for p in preguntas%}
                    <p class="card-text" style="font-weight: bold";>Pregunta: {{p.pregunta}}</p>
                    <p class="card-text">{{p.op1}}</p>
                    <p class="card-text">{{p.op2}}</p>
                    <p class="card-text">{{p.op3}}</p>
                    <p class="card-text">{{p.op4}}</p>
                    <p class="card-text" style="font-weight: bold";> La respuesta correcta era la {{p.respuesta}}</p>
                    {% endfor %}

            </div>
        </div>

    </div>
</div>
 
</div>
 
{% endblock %}